# datasource configurations
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: 123321
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# logs configurations
logging:
  file:
    path: ./logs
  level:
    org:
      vendetta: debug
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
      springframework:
        jdbc:
          core: debug